apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-pool
  namespace: g-404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-pool
  template:
    metadata:
      labels:
        app: transaction-pool
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: transaction-pool
          image: ghcr.io/renzrob/transaction-pool:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ticketchain-config
          volumeMounts:
            - name: tls-cert       # cert+key propio (server del ingress y client al gateway)
              mountPath: /certs
              readOnly: true
            - name: ca-cert        # CA para verificar al mining-gateway
              mountPath: /ca
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: trp-tls
        - name: ca-cert
          secret:
            secretName: cross-cluster-ca
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-pool
  namespace: g-404
spec:
  type: ClusterIP
  selector:
    app: transaction-pool
  ports:
    - port: 8000
      targetPort: 8000
