apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-gpu
  namespace: g-404
spec:
  replicas: 1
  strategy:
    type: Recreate   # 1 sola GPU: matar el pod viejo antes de crear el nuevo
  selector:
    matchLabels:
      app: worker-gpu
  template:
    metadata:
      labels:
        app: worker-gpu
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker-gpu
          image: ghcr.io/renzrob/worker-gpu:latest
          envFrom:
            - configMapRef:
                name: ticketchain-config
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "1"
              memory: "1Gi"
              nvidia.com/gpu: "1"
