apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketchain-config
  namespace: g-404
data:
  # Conexiones internas (no sensibles)
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  # MinIO (no sensible)
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_BUCKET: "ticketchain"
  # App
  CORS_ORIGIN: "https://ticketchain404.duckdns.org"
  PUBLIC_API_URL: "https://ticketchain404.duckdns.org"
  MINING_DIFFICULTY: "3"
  NODE_ENV: "production"
  # Modelo PULL: el gateway no llama al TrP (el TrP hace polling). No hace falta TRP_URL.
