apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: g-404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-service
          image: ghcr.io/renzrob/auth-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: ticketchain-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ticketchain-secrets
                  key: JWT_SECRET
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ticketchain-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketchain-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/ticketchain"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: g-404
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 3001
      targetPort: 3001
