apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-gpu
  namespace: g-404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-gpu
  template:
    metadata:
      labels:
        app: worker-gpu
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker-gpu
          image: ghcr.io/renzrob/worker-gpu:latest
          envFrom:
            - configMapRef:
                name: ticketchain-config
            - secretRef:
                name: ticketchain-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "2"
              memory: "2Gi"
              nvidia.com/gpu: "1"
