apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - g-404
  selector:
    matchLabels:
      app: transaction-api
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
