apiVersion: v1
kind: Secret
metadata:
  name: ticketchain-secrets
  namespace: ticketchain
type: Opaque
data:
  # echo -n "value" | base64
  JWT_SECRET: dGlja2V0Y2hhaW5fZGV2X3NlY3JldF9jaGFuZ2VfaW5fcHJvZA==
  POSTGRES_USER: dGlja2V0Y2hhaW4=
  POSTGRES_PASSWORD: dGlja2V0Y2hhaW4=
