events {
    worker_connections 1024;
}

http {
    client_max_body_size 10m;

    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        location /api/auth/ {
            set $backend "http://auth-service:3001";
            rewrite ^/api(/.*) $1 break;
            proxy_pass $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        location /api/events/ {
            set $backend "http://event-registry:3002";
            rewrite ^/api(/.*) $1 break;
            proxy_pass $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        location /api/transactions/ {
            set $backend "http://transaction-api:3003";
            rewrite ^/api(/.*) $1 break;
            proxy_pass $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        location /api/access/ {
            set $backend "http://access-control:3004";
            rewrite ^/api(/.*) $1 break;
            proxy_pass $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        location /api/status/ {
            set $backend "http://status-api:3005";
            rewrite ^/api/status(/.*)?$ $1 break;
            proxy_pass $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        location /images/ {
            set $backend "http://minio:9000";
            rewrite ^/images/(.*) /ticketchain/$1 break;
            proxy_pass $backend;
            proxy_set_header Host minio;
        }

        location / {
            set $backend "http://frontend:5173";
            proxy_pass $backend$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }
    }
}
