apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-control
  namespace: g-404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-control
  template:
    metadata:
      labels:
        app: access-control
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: access-control
          image: ghcr.io/renzrob/access-control:latest
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: ticketchain-config
            - secretRef:
                name: ticketchain-secrets
          resources:
            # "m" = millicores: 1000m = 1 CPU. 100m = 10% de un núcleo (idle), 500m = 50% (límite máximo)
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: access-control
  namespace: g-404
spec:
  type: ClusterIP
  selector:
    app: access-control
  ports:
    - port: 3004
      targetPort: 3004
