apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: access-control-hpa
  namespace: g-404
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: access-control
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
