apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-registry
  namespace: g-404
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-registry
  template:
    metadata:
      labels:
        app: event-registry
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: event-registry
          image: ghcr.io/renzrob/event-registry:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: ticketchain-config
            - secretRef:
                name: ticketchain-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: event-registry
  namespace: g-404
spec:
  type: ClusterIP
  selector:
    app: event-registry
  ports:
    - port: 3002
      targetPort: 3002
